In [1]:
%load_ext autoreload
%autoreload 2


In [2]:
import numpy as np
import wimpy
a = np.array(['apple', 'orange', 'apple', 'banana'])
a = np.array([a, a, a])
arr_index = np.where(a == 'apple')
print(arr_index)
print(a[arr_index])

(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 2, 0, 2]))
['apple' 'apple' 'apple' 'apple' 'apple' 'apple']


In [3]:
x = np.array(['123', '234'])
np.array([x, x])

array([['123', '234'],
       ['123', '234']], dtype='<U3')

In [4]:
a

array([['apple', 'orange', 'apple', 'banana'],
       ['apple', 'orange', 'apple', 'banana'],
       ['apple', 'orange', 'apple', 'banana']], dtype='<U6')

In [10]:
seqs = ['ATGCAAAA', 'TAGCATGA']
ref = 'ATGCAAA'
indices = wimpy.tilepin_v2(seqs, ref, tile_len=3)
indices


['ATG' 'TGC' 'GCA' 'CAA' 'AAA']
[['ATG' 'TGC' 'GCA' 'CAA' 'AAA' 'AAA']
 ['TAG' 'AGC' 'GCA' 'CAT' 'ATG' 'TGA']]


[[array([0]), array([1]), array([2]), array([3]), array([4, 5])],
 [array([4]),
  array([], dtype=int64),
  array([2]),
  array([], dtype=int64),
  array([], dtype=int64)]]

In [25]:
np.unique([1, 2, 3, 1, 2], return_inverse=True)

(array([1, 2, 3]), array([0, 1, 2, 0, 1]))

In [12]:
np.concatenate([[1, 2], [], [3]])

array([1., 2., 3.])

In [14]:
a = [1, 2, 3, 3]
d = {a: i for i, a in enumerate(a)}
d

{1: 0, 2: 1, 3: 3}